/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JobsJobIdRouteImport } from './routes/jobs.$jobId'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedInterviewsRouteImport } from './routes/_authenticated/interviews'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCandidatesRouteImport } from './routes/_authenticated/candidates'
import { Route as AuthenticatedJobsNewRouteImport } from './routes/_authenticated/jobs.new'
import { Route as AuthenticatedJobsJobIdPipelineRouteImport } from './routes/_authenticated/jobs.$jobId.pipeline'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsJobIdRoute = JobsJobIdRouteImport.update({
  id: '/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInterviewsRoute = AuthenticatedInterviewsRouteImport.update({
  id: '/interviews',
  path: '/interviews',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCandidatesRoute = AuthenticatedCandidatesRouteImport.update({
  id: '/candidates',
  path: '/candidates',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJobsNewRoute = AuthenticatedJobsNewRouteImport.update({
  id: '/jobs/new',
  path: '/jobs/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJobsJobIdPipelineRoute =
  AuthenticatedJobsJobIdPipelineRouteImport.update({
    id: '/jobs/$jobId/pipeline',
    path: '/jobs/$jobId/pipeline',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/candidates': typeof AuthenticatedCandidatesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/interviews': typeof AuthenticatedInterviewsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/jobs/new': typeof AuthenticatedJobsNewRoute
  '/jobs/$jobId/pipeline': typeof AuthenticatedJobsJobIdPipelineRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/candidates': typeof AuthenticatedCandidatesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/interviews': typeof AuthenticatedInterviewsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/jobs/new': typeof AuthenticatedJobsNewRoute
  '/jobs/$jobId/pipeline': typeof AuthenticatedJobsJobIdPipelineRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/candidates': typeof AuthenticatedCandidatesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/interviews': typeof AuthenticatedInterviewsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/_authenticated/jobs/new': typeof AuthenticatedJobsNewRoute
  '/_authenticated/jobs/$jobId/pipeline': typeof AuthenticatedJobsJobIdPipelineRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/candidates'
    | '/dashboard'
    | '/interviews'
    | '/profile'
    | '/jobs/$jobId'
    | '/jobs/new'
    | '/jobs/$jobId/pipeline'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/candidates'
    | '/dashboard'
    | '/interviews'
    | '/profile'
    | '/jobs/$jobId'
    | '/jobs/new'
    | '/jobs/$jobId/pipeline'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/sitemap.xml'
    | '/_authenticated/candidates'
    | '/_authenticated/dashboard'
    | '/_authenticated/interviews'
    | '/_authenticated/profile'
    | '/jobs/$jobId'
    | '/_authenticated/jobs/new'
    | '/_authenticated/jobs/$jobId/pipeline'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  JobsJobIdRoute: typeof JobsJobIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$jobId': {
      id: '/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof JobsJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/interviews': {
      id: '/_authenticated/interviews'
      path: '/interviews'
      fullPath: '/interviews'
      preLoaderRoute: typeof AuthenticatedInterviewsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/candidates': {
      id: '/_authenticated/candidates'
      path: '/candidates'
      fullPath: '/candidates'
      preLoaderRoute: typeof AuthenticatedCandidatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/jobs/new': {
      id: '/_authenticated/jobs/new'
      path: '/jobs/new'
      fullPath: '/jobs/new'
      preLoaderRoute: typeof AuthenticatedJobsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/jobs/$jobId/pipeline': {
      id: '/_authenticated/jobs/$jobId/pipeline'
      path: '/jobs/$jobId/pipeline'
      fullPath: '/jobs/$jobId/pipeline'
      preLoaderRoute: typeof AuthenticatedJobsJobIdPipelineRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCandidatesRoute: typeof AuthenticatedCandidatesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedInterviewsRoute: typeof AuthenticatedInterviewsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedJobsNewRoute: typeof AuthenticatedJobsNewRoute
  AuthenticatedJobsJobIdPipelineRoute: typeof AuthenticatedJobsJobIdPipelineRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCandidatesRoute: AuthenticatedCandidatesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedInterviewsRoute: AuthenticatedInterviewsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedJobsNewRoute: AuthenticatedJobsNewRoute,
  AuthenticatedJobsJobIdPipelineRoute: AuthenticatedJobsJobIdPipelineRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  JobsJobIdRoute: JobsJobIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
